# Site
name: "ÇeVeri"
title: "Çeveri Blog"
description: "Çeveri Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon'
baseurl: ""
google_analytics: 'UA-46278016-1'
disqus: 'ceveri'
mailchimp-list: ''
include: ["_pages"]
permalink: /blog/:title/

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: ""
    twitter: https://twitter.com
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: ""
    web: "https://github.com/barocena"
    twitter: https://twitter.com
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  Barocena:
    name: Barocena
    display_name: Barış
    surname: Şentürk
    avatar: "assets/images/Barocena.png"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: ""
    web: "https://github.com/barocena"
    twitter: https://instagram.com/barocena
    description: "KLU | Translation and Interpreting"
  Aleyna:
    name: Aleyna
    display_name: Aleyna
    surname: Şen
    avatar: 'assets/images/aleyna.png'
    web: "https://www.instagram.com/nesanyela/"
    twitter: "https://www.instagram.com/nesanyela/"
    description: "KLU | Translation and Interpreting"
  Omer:
    name: Ömer
    display_name: Ömer Faruk
    surname: Türkan
    avatar: 'assets/images/omer_pp.jpg'
    web: "https://www.linkedin.com/in/ömer-faruk-türkan-724141237/"
    twitter: "https://www.linkedin.com/in/ömer-faruk-türkan-724141237/"
    description: "KLU | Translation and Interpreting"
  Sevda:
    name: Sevda
    display_name: Sevda
    surname: Pekcoşkun Güner
    avatar: 'assets/images/sevda_hoca.jfif'
    web: "https://www.linkedin.com/in/sevda-pekcoşkun-güner-b4093582/"
    twitter: "https://www.linkedin.com/in/sevda-pekcoşkun-güner-b4093582/"
    description: "Dr. Öğretim Üyesi / Kırklareli University"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "pub-7974529656478107"
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
